<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Kitchen;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $category = Category::all();
        $kitchen = Kitchen::all();

        $data = [
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TARIK PANAS", "price" => 16000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TARIK DINGIN", "price" => 22000, "cogp" => 4954],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TARIK CINCAU", "price" => 25000, "cogp" => 5954],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TARIK HIJAU PANAS", "price" => 16000, "cogp" => 6200],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TARIK HIJAU DINGIN", "price" => 22000, "cogp" => 6700],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TARIK HIJAU CINCAU DINGIN", "price" => 25000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH MANIS PANAS", "price" => 8000, "cogp" => 1704],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH MANIS DINGIN", "price" => 10000, "cogp" => 2704],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TAWAR PANAS", "price" => 6000, "cogp" => 1454],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH TAWAR DINGIN", "price" => 7000, "cogp" => 1954],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH HIJAU MANIS PANAS", "price" => 10000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH HIJAU MANIS DINGIN", "price" => 14000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH HIJAU TAWAR PANAS", "price" => 8000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH HIJAU TAWAR DINGIN", "price" => 10000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH BMW", "price" => 22000, "cogp" => 5704],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH HIJAU SUSU PANAS", "price" => 15000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH HIJAU SUSU DINGIN", "price" => 18000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "GRENTEA CINCAU", "price" => 22000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "LEMON TEA MANUAL PANAS", "price" => 15000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "LEMON TEA MANUAL DINGIN", "price" => 18000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "LEMON TEA SACHET PANAS", "price" => 10000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "LEMON TEA SACHET DINGIN", "price" => 12000, "cogp" => 0],
            ["category" => "Teh Tarik", "kitchen" => "Dapur 3", "name" => "TEH BMW", "price" => 18000, "cogp" => 0],

            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "KOPI SARING HITAM PANAS", "price" => 15000, "cogp" => 3250],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "KOPI SARING HITAM DINGIN", "price" => 18000, "cogp" => 3250],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "KOPI SARING PANCONG", "price" => 12000, "cogp" => 0],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "SANGER PANAS", "price" => 16000, "cogp" => 4000],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "SANGER DINGIN", "price" => 22000, "cogp" => 5500],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "SANGER PANCONG", "price" => 12000, "cogp" => 0],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "KOPI BMW", "price" => 22000, "cogp" => 0],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "KOPI BMW SPESIAL", "price" => 25000, "cogp" => 0],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "ES KOSONG", "price" => 5000, "cogp" => 1000],
            ["category" => "Kopi Saring", "kitchen" => "Dapur 4", "name" => "ES BATU", "price" => 3000, "cogp" => 0],

            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS JERUK", "price" => 18000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS MANGGA", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS ALPUKAT", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS BUAH NAGA", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS APEL", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS MELON", "price" => 15000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS SUNKIS", "price" => 25000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS SEMANGKA", "price" => 15000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS SIRSAK", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS WORTEL + JERUK", "price" => 25000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JUS APEL HIJAU", "price" => 23000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "LEMON TEA WAG", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "LEMON MADU", "price" => 25000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "GREEN TEA LEMON SEREH MADU", "price" => 28000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "JAHE LEMON MADU SEREH", "price" => 28000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "BUAH POTONG PILIHAN", "price" => 35000, "cogp" => 0],
            ["category" => "Minuman Jus", "kitchen" => "Dapur 3", "name" => "BUAH POTONG WAG", "price" => 30000, "cogp" => 0],

            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "MILO PANAS", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "MILO DINGIN", "price" => 13000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "LEMON TEA PANAS", "price" => 15000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "LEMON TEA DINGIN", "price" => 18000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "LCYHEE TEA DINGIN", "price" => 22000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "MINERAL PRISTINE", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "MINERAL AMIDIS", "price" => 5000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "SIRUP KURNIA", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "SUSU BERUANG", "price" => 20000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "TIMUN SERUT", "price" => 25000, "cogp" => 3666],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "PEPAYA SERUT CINCAU", "price" => 25000, "cogp" => 4422],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "TELUR AYAM KAMPUNG 1/2 MATANG ( 2 TELUR)", "price" => 18000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "TELUR AYAM KAMPUNG 1/2 MATANG ( 3 TELUR)", "price" => 23000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "KOPI BMW", "price" => 18000, "cogp" => 9000],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "KOPI BMW SPESIAL (NESCAFE / MILO)", "price" => 25000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "ES KOSONG", "price" => 3000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "NESCAFE PANAS", "price" => 7000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "NESCAFE DINGIN", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "MILO PANAS", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "MILO DINGIN", "price" => 13000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "CAPPUCINO PANAS", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "CAPPUCINO DINGIN ", "price" => 13000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "COFFEMIX PANAS", "price" => 7000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "COFFEMIX DINGIN", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "LUWAK WHITE COFFEE PANAS", "price" => 7000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "LUWAK WHITE COFFEE DINGIN", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "BEMBENG COKLAT PANAS", "price" => 8000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "BEMBENG COKLAT DINGIN", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "NUTRI SARI JERUK NIPIS", "price" => 10000, "cogp" => 0],
            ["category" => "Minuman Lainnya", "kitchen" => "Dapur 4", "name" => "NUTRI SARI ORANGE", "price" => 10000, "cogp" => 0],

            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "FANTA", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "FANTA  SUSU", "price" => 15000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "SPRITE", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "COCA COLA", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "SODA SUSU", "price" => 17000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "TEBS", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "FRUTEA", "price" => 12000, "cogp" => 0],
            ["category" => "Minuman Float", "kitchen" => "Dapur 3", "name" => "TEH BOTOL", "price" => 12000, "cogp" => 0],

            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH BIASA", "price" => 18000, "cogp" => 6600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH TELUR", "price" => 25000, "cogp" => 8600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH SEAFOOD", "price" => 38000, "cogp" => 26600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH DAGING", "price" => 33000, "cogp" => 14600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH UDANG", "price" => 33000, "cogp" => 16600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH CUMI CUMI", "price" => 33000, "cogp" => 16600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH KEPITING ( 1 ONS KEPITING 30 RIBU)", "price" => 48000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH LOBSTER ( 1 ONS LOBSTER 30 RIBU)", "price" => 53000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "MIE ACEH SPECIAL", "price" => 50000, "cogp" => 34600],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE BIASA", "price" => 18000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE TELUR", "price" => 25000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE UDANG", "price" => 33000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE DAGING", "price" => 33000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE CUMI - CUMI", "price" => 33000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE SPECIAL", "price" => 50000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE BANGLADESH / BECEK", "price" => 25000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE SEAFOOD", "price" => 38000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE KEPITING ( 1 ONS KEPITING 30 RIBU)", "price" => 48000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "INDOMIE LOBSTER ( 1 ONS LOBSTER 35 RIBU)", "price" => 53000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG BIASA", "price" => 18000, "cogp" => 9900],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG KEUMAMAH", "price" => 28000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG KAMBING", "price" => 55000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG KAMPUNG BIASA", "price" => 35000, "cogp" => 12500],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG KAMPUNG SEAFOOD", "price" => 45000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "SPESIAL NASI KEUNEBAH INDATU", "price" => 15000, "cogp" => 0],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG DAGING", "price" => 33000, "cogp" => 17900],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG CUMI CUMI", "price" => 33000, "cogp" => 19900],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG UDANG", "price" => 33000, "cogp" => 19900],
            ["category" => "Makanan", "kitchen" => "Dapur 1", "name" => "NASI GORENG SEAFOOD", "price" => 45000, "cogp" => 29900],

            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI ORIGINAL / POLOS", "price" => 10000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI GULA", "price" => 12000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI SUSU", "price" => 15000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI SUSU KEJU", "price" => 18000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI OVOMALTINE", "price" => 25000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI NUTELLA", "price" => 25000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI DURIAN", "price" => 25000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "ROTI BAKAR OVOMALTINE", "price" => 20000, "cogp" => 9800],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "ROTI BAKAR NUTELLA", "price" => 20000, "cogp" => 9800],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "ROTI BAKAR NUTELLA KEJU", "price" => 23000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "ROTI BAKAR KEJU SUSU", "price" => 18000, "cogp" => 6800],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "KAYA TOAST", "price" => 30000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "MARTABAK TELUR WAG", "price" => 20000, "cogp" => 7500],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "MARTABAK DAGING", "price" => 30000, "cogp" => 15500],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "MARTABAK UDANG", "price" => 35000, "cogp" => 17500],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "MARTABAK SPESIAL (UDANG + DAGING)", "price" => 50000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI SATE MATANG + KUAH SOTO (SPESIAL)", "price" => 60000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI SATE MATANG + KUAH SOTO (BIASA) 10 TUSUK", "price" => 55000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI SATE MATANG + KUAH SOTO (BIASA) 5 TUSUK", "price" => 35000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA ORIGINAL", "price" => 10000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA TELUR", "price" => 20000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA SAYUR", "price" => 20000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA DAGING SPESIAL", "price" => 30000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA DAGING KAMBING", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA TELUR + KARI KAMBING", "price" => 70000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "KAYA TOAST + TELUR 1/2 MATANG + TEH TARIK PANAS (PAKET A)", "price" => 52000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "KAYA TOAST + TELUR 1/2 MATANG + SANGER PANAS (PAKET B)", "price" => 20000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CANAI PRATA TELUR + KUAH KARI KAYA TOAST + TEH TARIK PANAS (PAKET C)", "price" => 20000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "TELOR MATA SAPI", "price" => 10000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "TELOR DADA", "price" => 12500, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "ESKTRA DAGING", "price" => 20000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "EKSTRA UDANG", "price" => 15000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "EKSTRA CUMI", "price" => 15000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "KERUPUK EMPING", "price" => 5000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LOBSTER KARI 1 ONS ( SUDAH DIBERSIHKAN DAN SIAP SAJI)", "price" => 18000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "KEPITING KARI 1 ONS ( SUDAH DIBERSIHKAN DAN SIAP SAJI)", "price" => 28000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "CUMI TEUPELEUMAK 1 ONS", "price" => 30000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "SOP BUNTUT", "price" => 75000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "BEBEK MASAK MERAH + NASI", "price" => 40000, "cogp" => 22500],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "BEBEK MASAK PUTIH + NASI", "price" => 40000, "cogp" => 21500],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "BEBEK PUTIH BAKAR", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "BEBEK MERAH BAKAR", "price" => 45000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "BEBEK GORENG REMPAH", "price" => 45000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "UDANG PEULEMAK 1 ONS", "price" => 25000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI GURIH + TELUR BALADO", "price" => 32000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI GURIH + GULAI AYAM", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI GURIH + RENDANG", "price" => 43000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI GURIH + RENDANG + TELUR", "price" => 53000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI GURIH + AYAM + TELUR", "price" => 53000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI GURIH + AYAM + RENDANG", "price" => 63000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LONTONG + TELUR BALADO", "price" => 32000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LONTONG + GULAI AYAM", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LONTONG + RENDANG", "price" => 43000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LONTONG + RENDANG + TELUR", "price" => 53000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LONTONG + AYAM + TELUR", "price" => 53000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "LONTONG + AYAM + RENDANG", "price" => 63000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "MIE KOCOK POLOS", "price" => 33000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "MIE KOCOK KOMPLIT", "price" => 38000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "SOTO AYAM", "price" => 35000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "SOTO DAGING", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "PERKEDEL", "price" => 8000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + AYAM TANGKAP", "price" => 45000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + AYAM MASAK ACEH", "price" => 47000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + AYAM PRAMUGARI", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + DAGING BALADO", "price" => 48000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + DAGING SIE REUBOH", "price" => 48000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + IKAN KAYU", "price" => 35000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + IKAN TENGGIRI BALADO", "price" => 40000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + TELUR DEDAH", "price" => 35000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + TELUR SUNTI", "price" => 30000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + PEPES TERI", "price" => 25000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + PEPES KEMBUNG", "price" => 30000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + PEPES GORENG", "price" => 35000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + PEPES UDANG", "price" => 35000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "NASI + KUAH BEULANGGONG", "price" => 48000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "KUAH PLIEK 'U", "price" => 25000, "cogp" => 0],
            ["category" => "snack", "kitchen" => "Dapur 2", "name" => "SAMBAL UDANG", "price" => 20000, "cogp" => 0],
        ];

        foreach ($data as $key => $item) {
            Product::create([
                'cogp' => $item['cogp'] ?? 0,
                'image' => $item['image'] ?? Storage::url('image-default.jpg'),
                'name' => $item['name'],
                'price' => $item['price'],
                'stock' => $item['stock'] ?? 20,

                'category_id' => $category->firstWhere('name', $item['category'])?->id ?? $category->random()->id,
                'kitchen_id' => $kitchen->firstWhere('name', $item['kitchen'])?->id ?? $kitchen->random()->id,
            ]);
        }
    }
}
